#!/usr/bin/env python3
"""Verify a Grous AI release APK — no Android SDK or Java required.

What this tool checks (pure Python, stdlib only):

  1. ZIP integrity        every entry decompresses with a valid CRC-32.
  2. Manifest audit       decodes the binary AndroidManifest.xml with a
                          built-in AXML parser and reports package, version,
                          min/target SDK, permissions, activities, debuggable.
  3. Permission baseline  FAILS if the APK requests any permission outside
                          PERMISSION_BASELINE (INTERNET + the app's own
                          signature-level permission).
  4. Release sanity       FAILS if the package name is wrong.  Being built
                          debuggable is a WARNING by default (promoted to a
                          hard failure with --strict), as is a debug-keystore
                          signing certificate.
  5. Signature detection  locates the APK Signing Block (v2/v3) via the ZIP
                          End-Of-Central-Directory record and reports which
                          schemes are present.
  6. Signing certificate  extracts the signer certificate from the v2/v3
                          block (layout-agnostic DER scan) and reports its
                          subject, key size and SHA-256 fingerprint.
                          WARNs when the key looks like the Android debug
                          keystore — a debug-signed APK is not a release key.
  7. v1 JAR integrity     verifies every file digest recorded in
                          META-INF/MANIFEST.MF against the actual APK bytes
                          (handles the JAR spec's 75-char Name truncation and
                          SHA-256-Digest labels). A mismatch = tampering and
                          FAILS the build. Also cross-checks the CERT.SF
                          section digests against MANIFEST.MF and REPORTS any
                          inconsistency (a common artifact of third-party
                          re-signing tools; on Android 7.0+ the v2 block is
                          the authoritative signature, so this is a warning,
                          not a hard failure).
  8. SHA-256              prints the artifact hash for pinning.

Hard failures (always): not-a-zip / corrupt zip, wrong package name,
unexpected permissions, no signature at all, v1 file-digest mismatch
(tampering).

Warnings (pass by default): signed with the Android debug keystore, built
debuggable, v1-only signature (no v2/v3 block), v1 CERT.SF<->MANIFEST
inconsistency, uncovered entries.  Run with --strict to promote the
debug-keystore and debuggable warnings to hard failures (the correct gate
for a production release).

Exit code 0 = pass (warnings allowed), 1 = fail, 2 = usage/IO error.

Usage:
    python3 apk_verify.py <path-to-apk> [--report-dir DIR] [--json] [--strict]
"""
import base64
import hashlib
import json
import os
import struct
import sys
import zipfile

# Permissions a Grous AI release APK is allowed to request.
# Anything else fails the audit — add a new entry only with an explicit
# decision recorded in the PR/commit message.
PERMISSION_BASELINE = {
    'android.permission.INTERNET',
    # auto-generated by AGP for ContextCompat.registerReceiver(...,
    # RECEIVER_NOT_EXPORTED); signature-protected, internal to the package
    'com.grous.ai.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION',
}

EXPECTED_PACKAGE = 'com.grous.ai'

# APK Signing Block magic: "APK Sig Block 42" (16 bytes)
SIGNING_MAGIC = b'APK Sig Block 42'
SCHEME_IDS = {
    0x7109871a: 'v2',
    0xf05368c0: 'v3',
    0x1b93ad61: 'v3.1',
}

# JAR spec: "Name:" lines must not exceed 75 characters; long entry names
# are truncated to 75 chars in the signature files.
JAR_NAME_LIMIT = 75

# RSA OID 1.2.840.113549.1.1 — used to recognise X.509 cert / SPKI blobs.
RSA_OID = b'\x06\x09\x2a\x86\x48\x86\xf7\x0d\x01\x01\x01'


class Failure(Exception):
    pass


def _u16(b, o):
    return struct.unpack_from('<H', b, o)[0]


def _i32(b, o):
    return struct.unpack_from('<i', b, o)[0]


def _u32(b, o):
    return struct.unpack_from('<I', b, o)[0]


# --------------------------------------------------------------------------
# AXML (binary XML) parser — string pool + element/attribute walk
# --------------------------------------------------------------------------

class Axml:
    def __init__(self, data):
        self.data = data
        if len(data) < 16 or _u16(data, 0) != 0x0003:
            raise ValueError('not an AXML file')
        off = 8
        if _u16(data, off) != 0x0001:
            raise ValueError('no string pool')
        self.sp_size = _u32(data, off + 4)
        self.n_strings = _u32(data, off + 8)
        self.is_utf8 = bool(_u32(data, off + 16) & (1 << 8))
        self.str_start = _u32(data, off + 20)
        self.str_offs = [_u32(data, off + 28 + i * 4)
                         for i in range(self.n_strings)]
        self.base = off + self.str_start
        self.strings = [self._read_string(i) for i in range(self.n_strings)]
        # resource-id map (0x0180 chunk)
        o = off + self.sp_size
        self.res_ids = []
        while o < len(data):
            t = _u16(data, o)
            csize = _u32(data, o + 4)
            if t == 0x0180:
                n = (csize - 8) // 4
                self.res_ids = [_u32(data, o + 8 + i * 4) for i in range(n)]
                break
            o += csize

    def _varint(self, p):
        x = self.data[p]
        if x & 0x80:
            return ((x & 0x7F) << 8) | self.data[p + 1], p + 2
        return x, p + 1

    def _read_string(self, idx):
        if idx is None or idx < 0 or idx >= self.n_strings:
            return ''
        p = self.base + self.str_offs[idx]
        if self.is_utf8:
            _, p = self._varint(p)
            blen, p = self._varint(p)
            return self.data[p:p + blen].decode('utf-8', 'replace')
        n = _u16(self.data, p)
        p += 2
        return self.data[p:p + n * 2].decode('utf-16-le', 'replace')

    def s(self, idx):
        if idx is None or idx < 0 or idx >= self.n_strings:
            return ''
        return self.strings[idx]

    def walk(self):
        """Yield (tag, {attr: value}) for start tags, in document order."""
        o = 8 + self.sp_size
        while o < len(self.data):
            t = _u16(self.data, o)
            hsize = _u16(self.data, o + 2)
            csize = _u32(self.data, o + 4)
            if t == 0x0102:  # RES_XML_START_ELEMENT
                ext = o + hsize
                name = self.s(_i32(self.data, ext + 4))
                a_start = _u16(self.data, ext + 8)
                a_size = _u16(self.data, ext + 10)
                n_a = _u16(self.data, ext + 12)
                attrs = {}
                for i in range(n_a):
                    a = ext + a_start + i * a_size
                    raw = _i32(self.data, a + 8)
                    # Res_value: size(u16 @a+12) res0(u8 @a+14)
                    #           dataType(u8 @a+15) data(u32 @a+16)
                    ty = self.data[a + 15]
                    dv = _u32(self.data, a + 16)
                    if ty == 0x03:          # RES_VALUE_TYPE_STRING
                        val = self.s(dv) if raw < 0 else self.s(raw)
                    elif ty == 0x10:        # RES_VALUE_TYPE_INT_DEC
                        val = dv
                    elif ty == 0x11:        # RES_VALUE_TYPE_INT_HEX
                        val = '0x%x' % dv
                    elif ty == 0x12:        # RES_VALUE_TYPE_INT_BOOLEAN
                        val = bool(dv)
                    elif ty in (0x01, 0x1f):  # RES_VALUE_TYPE_REFERENCE
                        val = '@0x%08x' % dv
                    else:
                        val = self.s(raw) if raw >= 0 else str(dv)
                    # Attribute names are always present in the string pool;
                    # the resource-id map is only a secondary hint and can be
                    # misaligned, so prefer the string name.
                    an = self.s(_i32(self.data, a + 4))
                    if not an and i < len(self.res_ids) and self.res_ids[i]:
                        an = _RES_ID_NAMES.get(self.res_ids[i], '')
                    attrs[an] = val
                yield name, attrs
            o += csize


# android framework attribute resource-ids we care about
_RES_ID_NAMES = {
    0x01010003: 'package',
    0x01010004: 'label',
    0x01010006: 'debuggable',
    0x01010008: 'permission',
    0x0101000f: 'icon',
    0x01010010: 'theme',
    0x01010015: 'allowBackup',
    0x01010016: 'hardwareAccelerated',
    0x01010018: 'supportsRtl',
    0x01010019: 'largeHeap',
    0x01010020: 'backupAgent',
    0x01010023: 'name',
    0x01010024: 'value',
    0x01010029: 'platformBuildVersionCode',
    0x0101002a: 'versionCode',
    0x0101002b: 'versionName',
    0x0101002c: 'platformBuildVersionName',
    0x01010205: 'codeName',
    0x01010206: 'priority',
    0x01010207: 'persistent',
    0x01010209: 'launchMode',
    0x0101020a: 'enabled',
    0x0101020b: 'exported',
    0x0101020e: 'isolatedProcess',
    0x01010210: 'allowBackup',
    0x01010211: 'hardwareAccelerated',
    0x01010214: 'supportsRtl',
    0x01010215: 'directBootAware',
    0x01010217: 'largeHeap',
    0x01010218: 'supportsPictureInPicture',
    0x0101021b: 'roundIcon',
    0x0101021e: 'appComponentFactory',
    0x01010220: 'appCategory',
    0x01010221: 'resizeableActivity',
    0x01010222: 'usesCleartextTraffic',
    0x01010224: 'protectionLevel',
    0x0101026f: 'mainClassName',
    0x01010270: 'targetSdkVersion',
    0x01010271: 'minSdkVersion',
    0x01010400: 'configChanges',
    0x01010401: 'windowSoftInputMode',
    0x01010570: 'extractNativeLibs',
}


def decode_manifest(apk):
    """Return a structured view of the manifest."""
    with zipfile.ZipFile(apk) as z:
        data = z.read('AndroidManifest.xml')
    ax = Axml(data)
    out = {
        'package': None, 'versionCode': None, 'versionName': None,
        'minSdkVersion': None, 'targetSdkVersion': None,
        'platformBuildVersionCode': None, 'platformBuildVersionName': None,
        'debuggable': None, 'allowBackup': None,
        'usesCleartextTraffic': None, 'permissions': [],
        'declared_permissions': [], 'activities': [],
        'providers': [],
    }
    for tag, attrs in ax.walk():
        if tag == 'manifest':
            out['package'] = attrs.get('package')
            out['versionCode'] = attrs.get('versionCode')
            out['versionName'] = attrs.get('versionName')
            out['platformBuildVersionCode'] = attrs.get(
                'platformBuildVersionCode')
            out['platformBuildVersionName'] = attrs.get(
                'platformBuildVersionName')
        elif tag == 'uses-sdk':
            out['minSdkVersion'] = attrs.get('minSdkVersion')
            out['targetSdkVersion'] = attrs.get('targetSdkVersion')
        elif tag == 'uses-permission':
            out['permissions'].append(attrs.get('name'))
        elif tag == 'permission':
            out['declared_permissions'].append(
                {'name': attrs.get('name'),
                 'protectionLevel': attrs.get('protectionLevel')})
        elif tag == 'application':
            out['debuggable'] = attrs.get('debuggable')
            out['allowBackup'] = attrs.get('allowBackup')
            out['usesCleartextTraffic'] = attrs.get('usesCleartextTraffic')
        elif tag == 'activity':
            out['activities'].append(
                {'name': attrs.get('name'),
                 'exported': attrs.get('exported'),
                 'configChanges': attrs.get('configChanges'),
                 'windowSoftInputMode': attrs.get('windowSoftInputMode')})
        elif tag == 'provider':
            out['providers'].append(
                {'name': attrs.get('name'),
                 'authorities': attrs.get('authorities'),
                 'exported': attrs.get('exported')})
    return out, ax


# --------------------------------------------------------------------------
# APK Signing Block — located via EOCD, certificate extracted by DER scan
# --------------------------------------------------------------------------

def find_signing_block(raw):
    """Return (start, end, {scheme_id: value_bytes}) or None if v1-only.

    Tolerates trailing all-zero padding inside the block (some third-party
    signing tools, e.g. Signflinger, zero-fill the block without writing
    exact id-value entries all the way to the trailer). Non-zero stray bytes
    are still treated as corruption.
    """
    eocd = raw.rfind(b'PK\x05\x06')
    if eocd < 0:
        raise Failure('ZIP End-Of-Central-Directory record not found')
    cd_off = _u32(raw, eocd + 16)
    if cd_off < 32 or cd_off + 16 > len(raw):
        return None
    if raw[cd_off - 16:cd_off] != SIGNING_MAGIC:
        return None  # no APK Signing Block (v1-only APK)
    size = struct.unpack_from('<Q', raw, cd_off - 24)[0]
    if size < 32 or size > cd_off:
        raise Failure('corrupt signing block size field')
    start = cd_off - size
    end = cd_off
    entries = {}
    o = start + 8  # skip the leading size field
    trailer = end - 24  # second size field + magic
    while o + 8 <= trailer:
        chunk_id = _u32(raw, o)
        val_len = _u32(raw, o + 4)
        if o + 8 + val_len > trailer:
            raise Failure('corrupt signing block entry')
        if chunk_id or val_len:
            entries[chunk_id] = raw[o + 8:o + 8 + val_len]
        o += 8 + val_len
    if o != trailer:
        if any(raw[o:trailer]):
            raise Failure('corrupt signing block (unparsed trailing bytes)')
        # all-zero padding — tolerated
    return start, end, entries


def _der_len(data, o):
    ln = data[o]
    o += 1
    if ln & 0x80:
        n = ln & 0x7F
        ln = int.from_bytes(data[o:o + n], 'big')
        o += n
    return ln, o


def _der_items(data, o, end):
    """Yield (tag, value_bytes) for DER items in data[o:end]."""
    while o < end:
        tag = data[o]
        ln, o2 = _der_len(data, o + 1)
        yield tag, data[o2:o2 + ln]
        o = o2 + ln


def extract_cert(data):
    """Find the first X.509 certificate (DER) inside a byte blob.

    Layout-agnostic: scans for a long-form SEQUENCE whose contents look like
    an RSA certificate (RSA OID present, plausible length). Works for both
    standard apksigner v2 blocks and third-party (e.g. Signflinger) layouts.
    """
    i = 0
    n = len(data)
    while i < n - 4:
        if data[i] == 0x30 and data[i + 1] == 0x82:
            ln = (data[i + 2] << 8) | data[i + 3]
            end = i + 4 + ln
            if end <= n and 200 < ln < 20000 and RSA_OID in data[i:end]:
                return data[i:end]
            i += 4
        else:
            i += 1
    return None


def parse_cert_subject(cert):
    """Return a rough subject string (e.g. 'Android Debug') from a DER cert."""
    try:
        # Certificate ::= SEQ { tbs SEQ {...} , sigAlg, sig }
        outer = list(_der_items(cert, 0, len(cert)))
        tbs = outer[0][1]
        cn_oid = bytes.fromhex('0603550403')  # 2.5.4.3
        idx = tbs.find(cn_oid)
        if idx >= 0:
            seg = tbs[idx + len(cn_oid):idx + len(cn_oid) + 128]
            for tag, val in _der_items(seg, 0, len(seg)):
                if tag in (0x0C, 0x13, 0x16):  # UTF8 / Printable / IA5
                    return val.decode('utf-8', 'replace')
        # fallback: last human-readable string in the TBS
        strings = []

        def walk(b):
            for tag, val in _der_items(b, 0, len(b)):
                if tag in (0x0C, 0x13, 0x16):
                    strings.append(val.decode('utf-8', 'replace'))
                elif tag == 0x30:
                    walk(val)

        walk(tbs)
        return strings[-1] if strings else ''
    except Exception:
        return ''


def parse_cert_key_bits(cert):
    """Return the RSA public-key size in bits, or None."""
    try:
        cert_items = list(_der_items(cert, 0, len(cert)))
        if not cert_items or cert_items[0][0] != 0x30:
            return None
        # Certificate ::= SEQ { TBSCertificate, sigAlg, sigValue }
        contents = list(_der_items(cert_items[0][1], 0,
                                   len(cert_items[0][1])))
        if not contents or contents[0][0] != 0x30:
            return None
        tbscert = contents[0][1]  # TBSCertificate
        # SubjectPublicKeyInfo = SEQ { algId SEQ, BIT STRING }; it is the
        # last field of TBSCertificate. Identify it structurally so we don't
        # confuse it with Name (SEQ of SETs) or Validity (SEQ of times).
        for tag, val in _der_items(tbscert, 0, len(tbscert)):
            if tag != 0x30:
                continue
            sub = list(_der_items(val, 0, len(val)))
            if len(sub) == 2 and sub[0][0] == 0x30 and sub[1][0] == 0x03 \
                    and len(sub[1][1]) > 64:
                bitstring = sub[1][1]
                if not bitstring or bitstring[0] != 0:
                    continue
                key_items = list(_der_items(bitstring[1:], 0,
                                            len(bitstring) - 1))
                if not key_items or key_items[0][0] != 0x30:
                    continue
                keyseq = key_items[0][1]
                nums = [int.from_bytes(v, 'big')
                        for tt, v in _der_items(keyseq, 0, len(keyseq))
                        if tt == 0x02]
                if nums:
                    return nums[0].bit_length()
        return None
    except Exception:
        return None


def analyze_signing(raw):
    """Return a dict describing the signatures present in the APK."""
    res = find_signing_block(raw)
    out = {
        'schemes': [],
        'cert': None,
        'cert_subject': None,
        'cert_key_bits': None,
        'cert_sha256': None,
    }
    if res is None:
        return out
    _, _, entries = res
    out['schemes'] = [SCHEME_IDS.get(k, '0x%08x' % k) for k in entries]
    # prefer v2, then v3, then v3.1 for certificate extraction
    for scheme in ('v2', 'v3', 'v3.1'):
        if scheme in out['schemes']:
            sid = [k for k, v in SCHEME_IDS.items()
                   if v == scheme][0]
            cert = extract_cert(entries[sid])
            if cert:
                out['cert'] = cert
                out['cert_subject'] = parse_cert_subject(cert)
                out['cert_key_bits'] = parse_cert_key_bits(cert)
                out['cert_sha256'] = hashlib.sha256(cert).hexdigest()
                break
    return out


# --------------------------------------------------------------------------
# v1 JAR signature — file digests (hard) + section digests (report)
# --------------------------------------------------------------------------

def _jar_name(name):
    """JAR spec 75-char Name truncation."""
    return name if len(name) <= JAR_NAME_LIMIT else name[:JAR_NAME_LIMIT]


def _digest_value(line, label):
    if line.startswith(label + ': '):
        try:
            return base64.b64decode(line[len(label) + 2:].strip()).hex()
        except Exception:
            return None
    return None


def verify_v1_signature(zf):
    names = zf.namelist()
    if 'META-INF/MANIFEST.MF' not in names:
        return {'present': False}
    sf_names = [n for n in names
                if n.startswith('META-INF/') and n.endswith('.SF')]
    rsa_names = [n for n in names
                 if n.startswith('META-INF/') and
                 (n.endswith('.RSA') or n.endswith('.DSA') or n.endswith('.EC'))]
    out = {
        'present': True,
        'sf_files': sf_names,
        'signing_files': rsa_names,
        'manifest_entries': 0,
        'file_digests_verified': 0,
        'file_digest_mismatches': [],
        'uncovered_entries': [],
        'section_digests_checked': 0,
        'section_digest_mismatches': 0,
        'complete': bool(sf_names and rsa_names),
    }
    mf_text = zf.read('META-INF/MANIFEST.MF').decode('latin-1', 'replace')
    mf_lines = mf_text.splitlines()

    # map: jar-name -> sha256 hex
    manifest_digests = {}
    cur = None
    for line in mf_lines:
        if line.startswith('Name: '):
            cur = _jar_name(line[6:].strip())
            manifest_digests[cur] = None
        elif cur:
            d = _digest_value(line, 'SHA-256-Digest') or \
                _digest_value(line, 'SHA-256')
            if d:
                manifest_digests[cur] = d
    out['manifest_entries'] = len(manifest_digests)

    sig_files = {'META-INF/MANIFEST.MF'} | set(sf_names) | set(rsa_names)
    name_set = set(names)
    # (a) file digests vs actual bytes (truncation-aware)
    checked = 0
    for entry, dig in manifest_digests.items():
        if dig is None:
            continue
        norm = entry.lstrip('/')
        # find the real APK entry (may be longer than the truncated name)
        real = norm if norm in name_set else None
        if real is None:
            for n in name_set:
                if _jar_name(n) == entry:
                    real = n
                    break
        if real is None or real in sig_files:
            continue
        actual = hashlib.sha256(zf.read(real)).hexdigest()
        checked += 1
        if actual != dig:
            out['file_digest_mismatches'].append(real)
    out['file_digests_verified'] = checked
    covered = set(manifest_digests)
    for n in names:
        if n in sig_files or n.endswith('/'):
            continue
        if n not in covered and _jar_name(n) not in covered:
            out['uncovered_entries'].append(n)

    # (b) MANIFEST.MF section digests vs *.SF (informational)
    sections = {}
    cur = None
    for line in mf_lines:
        if line.startswith('Name: '):
            cur = line[6:].strip()
            sections[cur] = [line]
        elif line == '':
            cur = None
        elif cur is not None:
            sections[cur].append(line)
    for sf in sf_names:
        sf_text = zf.read(sf).decode('latin-1', 'replace')
        sf_lines = sf_text.splitlines()
        sf_pos = {}
        for i, ln in enumerate(sf_lines):
            if ln.startswith('Name: '):
                sf_pos[_jar_name(ln[6:].strip())] = i
        for entry, lines in sections.items():
            if entry not in sf_pos:
                continue
            norm = b''.join(l.rstrip('\r\n').encode('latin-1', 'replace')
                            + b'\n' for l in lines)
            expected = hashlib.sha256(norm).hexdigest()
            i = sf_pos[entry]
            got = None
            for j in range(i + 1, len(sf_lines)):
                d = _digest_value(sf_lines[j], 'SHA-256-Digest') or \
                    _digest_value(sf_lines[j], 'SHA-256')
                if d:
                    got = d
                    break
                if sf_lines[j].startswith('Name: ') or sf_lines[j] == '':
                    break
            if got is None:
                continue
            out['section_digests_checked'] += 1
            if got != expected:
                out['section_digest_mismatches'] += 1
    return out


# --------------------------------------------------------------------------
# Main
# --------------------------------------------------------------------------

def verify(apk_path, report_dir=None, strict=False):
    # issues that are warnings by default but hard failures under --strict
    strict_issues = []
    report = {
        'apk': os.path.basename(apk_path),
        'sha256': None,
        'zip_entries': 0,
        'signing': None,
        'v1': None,
        'manifest': None,
        'unexpected_permissions': [],
        'debuggable': None,
        'warnings': [],
        'errors': [],
        'passed': False,
    }
    warnings = report['warnings']

    # 1. ZIP integrity
    if not zipfile.is_zipfile(apk_path):
        raise Failure('not a valid ZIP/APK file')
    with zipfile.ZipFile(apk_path) as zf:
        bad = zf.testzip()
        if bad is not None:
            raise Failure(f'corrupt ZIP entry: {bad}')
        report['zip_entries'] = len(zf.namelist())
        # 7. v1 digest checks
        report['v1'] = verify_v1_signature(zf)
    with open(apk_path, 'rb') as f:
        raw = f.read()

    # 5. + 6. signature detection & certificate
    report['signing'] = analyze_signing(raw)
    sig = report['signing']

    # 2. + 3. + 4. manifest audit
    man, _ = decode_manifest(apk_path)
    report['manifest'] = man
    report['debuggable'] = man['debuggable']
    if man['package'] != EXPECTED_PACKAGE:
        raise Failure(f"package is {man['package']!r}, expected "
                      f"{EXPECTED_PACKAGE!r}")
    extra = [p for p in man['permissions'] if p not in PERMISSION_BASELINE]
    report['unexpected_permissions'] = extra
    if extra:
        raise Failure(f'unexpected permissions requested: {extra}')
    if man['debuggable'] not in (False, 0, None):
        strict_issues.append('built debuggable (android:debuggable="true") — '
                             'a debuggable build lets anyone attach a '
                             'debugger; rebuild with a release buildType')
    if man['usesCleartextTraffic']:
        warnings.append('usesCleartextTraffic="true" — cleartext (non-HTTPS) '
                        'traffic is permitted; keep this only if the app '
                        'intentionally calls plain-HTTP endpoints')
    if man['versionName'] is None or man['versionCode'] is None:
        warnings.append('versionCode/versionName missing from manifest')

    # signature verdict
    has_v2v3 = any(s in ('v2', 'v3', 'v3.1') for s in sig['schemes'])
    v1 = report['v1']
    if not has_v2v3 and not v1['present']:
        raise Failure('APK carries no signature (no v2/v3 block, no v1 files)')
    if not has_v2v3 and v1['present']:
        warnings.append('v1-only signature: installs via sideload, but a '
                        'release build should add a v2/v3 APK Signing Block '
                        '(required by the Play Store and by Android 7.0+ '
                        'verification)')

    # certificate findings
    subj = (sig['cert_subject'] or '')
    if sig['cert_sha256'] and 'debug' in subj.lower():
        msg = (f'signed with the Android DEBUG keystore (subject: {subj!r}) '
               f'— re-sign with a proper release key before wide '
               f'distribution; a debug key is machine-specific and cannot '
               f'sign future updates under a different key')
        strict_issues.append(msg)
        warnings.append(msg)
    if has_v2v3 and not sig['cert_sha256']:
        warnings.append('v2/v3 block present but no signer certificate '
                        'could be extracted')

    # v1 integrity findings
    if v1['present']:
        if v1['file_digest_mismatches']:
            raise Failure('v1 MANIFEST.MF file digests do not match the '
                          f'APK contents (tampering?): '
                          f"{v1['file_digest_mismatches'][:5]}")
        if v1['uncovered_entries']:
            warnings.append(f'{len(v1["uncovered_entries"])} APK entries are '
                            f'not covered by MANIFEST.MF')
        if v1['section_digests_checked']:
            mm = v1['section_digest_mismatches']
            if mm:
                warnings.append(
                    f'CERT.SF section digests disagree with MANIFEST.MF '
                    f'for {mm}/{v1["section_digests_checked"]} sections — '
                    f'a typical artifact of third-party re-signing; on '
                    f'Android 7.0+ the v2 block is authoritative, but '
                    f're-signing a release APK with an external tool is '
                    f'not recommended')
            if not v1['complete']:
                warnings.append('v1 signature files incomplete '
                                '(missing *.SF or *.RSA)')

    report['strict_issues'] = strict_issues
    if strict and strict_issues:
        raise Failure('strict mode — ' + ' | '.join(strict_issues))

    report['sha256'] = hashlib.sha256(raw).hexdigest()
    report['passed'] = True

    if report_dir:
        _write_report(report, report_dir)
    return report


def _write_report(report, report_dir):
    os.makedirs(report_dir, exist_ok=True)
    with open(os.path.join(report_dir, 'verify-report.json'), 'w') as f:
        json.dump(report, f, indent=2, default=str)
    with open(os.path.join(report_dir, 'sha256.txt'), 'w') as f:
        f.write(f"{report['sha256']}  {report['apk']}\n")
    m = report['manifest']
    sig = report['signing']
    v1 = report['v1']
    lines = [
        f"package:                 {m['package']}",
        f"version:                 {m['versionCode']} ({m['versionName']})",
        f"minSdkVersion:           {m['minSdkVersion']}",
        f"targetSdkVersion:        {m['targetSdkVersion']}",
        f"platformBuildVersion:    {m['platformBuildVersionCode']} "
        f"({m['platformBuildVersionName']})",
        f"debuggable:              {m['debuggable']}",
        f"allowBackup:             {m['allowBackup']}",
        f"usesCleartextTraffic:    {m['usesCleartextTraffic']}",
        f"zip entries:             {report['zip_entries']}",
        f"signing schemes:         "
        f"{', '.join(sig['schemes']) or 'none (v1-only)'}",
    ]
    if sig['cert_sha256']:
        lines.append(f"signing certificate:     {sig['cert_subject'] or 'n/a'}"
                     f" (RSA-{sig['cert_key_bits']})")
        lines.append(f"cert SHA-256:            {sig['cert_sha256']}")
    if v1['present']:
        lines.append(f"v1 manifest entries:     {v1['manifest_entries']}")
        lines.append(f"v1 file digests verified: {v1['file_digests_verified']}")
        lines.append(f"v1 section digests:      "
                     f"{v1['section_digests_checked'] - v1['section_digest_mismatches']}"
                     f"/{v1['section_digests_checked']} consistent")
    lines.append('permissions:')
    for p in m['permissions']:
        mark = 'ok ' if p in PERMISSION_BASELINE else '!!!'
        lines.append(f"  [{mark}] {p}")
    lines.append('activities:')
    for a in m['activities']:
        lines.append(f"  {a['name']} exported={a['exported']}")
    lines.append(f"SHA-256: {report['sha256']}")
    if report['warnings']:
        lines.append('warnings:')
        for w in report['warnings']:
            lines.append(f"  ! {w}")
    strict = report.get('strict_issues', [])
    unseen = [s for s in strict if s not in report['warnings']]
    if unseen:
        lines.append('strict-only issues (fail with --strict):')
        for s in unseen:
            lines.append(f"  # {s}")
    with open(os.path.join(report_dir, 'manifest-summary.txt'), 'w') as f:
        f.write('\n'.join(lines) + '\n')


def main():
    args = list(sys.argv[1:])
    report_dir = None
    as_json = '--json' in args
    strict = '--strict' in args
    for flag in ('--json', '--strict'):
        if flag in args:
            args.remove(flag)
    if '--report-dir' in args:
        i = args.index('--report-dir')
        report_dir = args[i + 1]
        del args[i:i + 2]
    if len(args) != 1:
        print(__doc__)
        return 2
    apk = args[0]
    if not os.path.isfile(apk):
        print(f'error: file not found: {apk}', file=sys.stderr)
        return 2
    try:
        report = verify(apk, report_dir, strict=strict)
    except Failure as e:
        print(f'FAIL  {e}', file=sys.stderr)
        print(f'      {apk}', file=sys.stderr)
        return 1
    m = report['manifest']
    sig = report['signing']
    print(f"PASS  {report['apk']}")
    print(f"      package    : {m['package']}")
    print(f"      version    : {m['versionCode']} ({m['versionName']})")
    print(f"      minSdk     : {m['minSdkVersion']}   targetSdk: "
          f"{m['targetSdkVersion']}")
    print(f"      permissions: {', '.join(m['permissions'])}")
    print(f"      signing    : {', '.join(sig['schemes']) or 'v1-only'}"
          + (f"  (cert: {sig['cert_subject']})" if sig['cert_subject'] else ''))
    print(f"      SHA-256    : {report['sha256']}")
    for w in report['warnings']:
        print(f"      warning  : {w}")
    for s in report.get('strict_issues', []):
        if s not in report['warnings']:
            print(f"      strict   : {s}  (use --strict to fail on this)")
    if as_json:
        print(json.dumps(report, indent=2, default=str))
    return 0


if __name__ == '__main__':
    sys.exit(main())
